version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --cleanup --label-enable
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/watchtower/config.json:/config.json:ro
    networks:
      - web
  
  traefik:
    container_name: traefik
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik/traefik.toml:/traefik.toml
      - ./etc/traefik/dynamic_conf.toml:/dynamic_conf.toml
      - ./etc/acme/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.traefik-redirect.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-redirect.middlewares=redirect@file"
      - "traefik.http.routers.traefik.middlewares=auth@file"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=default"
      - "traefik.http.routers.traefik.tls=true"
    networks:
      - web
    environment:
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.portainer-redirect.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer-redirect.middlewares=redirect@file"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web
    depends_on:
      - traefik

networks:
  web:
    external: true

